ci:
  autofix_prs: false
repos:
  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.3
    hooks:
      - id: build-docs
        args: ['--cache-dir', '_build/doctrees', '--html-dir', '_build/html', '--source-dir', './']
        language_version: python3